### PR TITLE
Enhance dj selection

### PR DESCRIPTION
**Pull request by lebull**
This PR does quite a lot of things:

* Enables organizers to add a dj to a lineup by searching for an existing one or quickly adding one into our db and to the event at the same time.
* Adjusts our schema to be more consistent in casing and reflect my idea of "copying" dj data into a slot instead of storing an actual dj.
* Adds a dj ref to the slot for tracking.
* Some very light ui cleanup, nothing too crazy.

THIS PR WILL BREAK BACKWARDS COMPATABILITY.  That's fine in this instance, we will need to adjust our schema at some point and the sooner, the better. I will go back and manually restore any data that I can.

### CODE REVIEW

**Comment by lebull** [comment]
Refactored "discord_username" to be "fur_name"

**Comment by icedog225** [comment]
We also have performers who aren't furries, so maybe we should call it something else besides fur name... IDK tho I'm drawing a blank on what else to call it :P

**Comment by icedog225** [comment]
hmmm and if we don't store a specific discord username anymore, how are we going to generate the text for pinging DJs for scheduling confirmation? is that gonna be in a different part of the data somewhere?

**Comment by lebull** [comment]
> hmmm and if we don't store a specific discord username anymore, how are we going to generate the text for pinging DJs for scheduling confirmation? is that gonna be in a different part of the data somewhere?

Not sure yet xD.

I'm going to spin up a ticket for figuring out a good option for handling discord stuff.  At the very least, I'm making the call that discord is out of scope for this change.

**Comment by lebull** [comment]
> We also have performers who aren't furries, so maybe we should call it something else besides fur name... IDK tho I'm drawing a blank on what else to call it :P



> We also have performers who aren't furries, so maybe we should call it something else besides fur name... IDK tho I'm drawing a blank on what else to call it :P

Good call

**Pull request merged**
