### PR TITLE
Moved to Vite

### PR DESCRIPTION
**Pull request by klAvAx**
Moved to Vite
Moved some dependencies to devDeps
Added vite-plugin-svgr
Added base jest setup
Removed redundant React import from a few places
Added new NPM script "lint"

### CODE REVIEW

**Comment by klAvAx** [comment]
Reverting back to draft since some additional stuff is required to do for a check pass

**Comment by klAvAx** [comment]
Marking as Ready for Review!

**Comment by lebull** [comment]
Changes look good and hoooooly crap, yeah, this is fast

**Comment by klAvAx** [comment]
Yeee, its pretty good 😅

**Review by lebull — APPROVED** [review]

**Pull request merged**
